@startuml

Actor User as U

box "Monaco Module in GLSP Client" #LightBlue
participant "Monaco Editor" as M

participant "Client A/O Handler" as H

end box

participant "GLSP Server" as S
U -> M: Types text
M -> H: onDidChangeModelContent
H -> S: UpdateValidationsAction

@enduml
