name: 'Setup Node and install packages'
description: 'Setup Node and install packages'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "yarn"
        registry-url: https://npm.pkg.github.com/
    - run: yarn install --immutable
      shell: bash